# Frontend Dockerfile
FROM node:18 AS deps
WORKDIR /app
COPY coincounter/package*.json ./
RUN npm install

FROM node:18 AS dev
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY coincounter/ ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
