# Generated by Django 5.2.7 on 2025-10-04 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=64, unique=True)),
                ('n_tx', models.IntegerField()),
                ('n_unredeemed', models.IntegerField(blank=True, null=True)),
                ('total_received', models.BigIntegerField(blank=True, null=True)),
                ('total_sent', models.BigIntegerField(blank=True, null=True)),
                ('final_balance', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('version', models.IntegerField()),
                ('lock_time', models.CharField(blank=True, max_length=64, null=True)),
                ('size', models.IntegerField()),
                ('relayed_by', models.GenericIPAddressField(blank=True, null=True)),
                ('block_height', models.IntegerField()),
                ('tx_index', models.CharField(max_length=64)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.address')),
            ],
        ),
    ]
