# Generated by Django 5.2.7 on 2025-10-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='final_balance',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='total_received',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='total_sent',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
